# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sw_coord_lat', models.FloatField()),
                ('sw_coord_long', models.FloatField()),
                ('ne_coord_lat', models.FloatField()),
                ('ne_coord_long', models.FloatField()),
                ('text_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Landmark')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Landmark'),
        ),
    ]
