# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('text_description', models.TextField(blank=True, default='', null=True)),
                ('priority', models.IntegerField(default=1)),
                ('attributes', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('gallery', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('landmarks', sortedm2m.fields.SortedManyToManyField(help_text=None, to='api.Landmark', verbose_name='list of landmarks')),
            ],
        ),
    ]
