# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='ne_coord_lat',
            new_name='nw_coord_lat',
        ),
        migrations.RenameField(
            model_name='landmark',
            old_name='ne_coord_long',
            new_name='nw_coord_long',
        ),
        migrations.RenameField(
            model_name='landmark',
            old_name='sw_coord_lat',
            new_name='se_coord_lat',
        ),
        migrations.RenameField(
            model_name='landmark',
            old_name='sw_coord_long',
            new_name='se_coord_long',
        ),
    ]
