# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='indoor_nav',
            field=models.BooleanField(default=False),
        ),
    ]
