# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0007_floor_level'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='building',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indoor.Building'),
        ),
    ]
