# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170210_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='landmark',
            old_name='ctr_coord_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='landmark',
            old_name='ctr_coord_long',
            new_name='long',
        ),
    ]
