# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='tour/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='polyline',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='text_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
