# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='landmark',
        ),
        migrations.AddField(
            model_name='landmark',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
