# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171010_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='polyline',
        ),
    ]
