# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('api', '0007_auto_20170407_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='gallery',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery'),
        ),
    ]
