# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_landmark_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
