# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tour_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
