# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170418_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='photoCount',
            field=models.IntegerField(default=0),
        ),
    ]
