# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_landmark_photocount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='photoCount',
            new_name='photo_count',
        ),
    ]
