# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170418_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='photo_count',
        ),
    ]
