# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
