# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170517_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
