# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 01:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170523_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='attributes',
            field=jsonfield.fields.JSONField(default='{\n    "key": "value"\n}'),
        ),
    ]
