# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 07:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_landmark_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='attributes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
