# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170529_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='text_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
