# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='mpoint',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='roompolygon',
            old_name='mpoly',
            new_name='geom',
        ),
    ]
