# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 06:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0002_auto_20170702_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=-1)),
            ],
        ),
    ]
