# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 06:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0003_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4236),
        ),
    ]
