# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0005_auto_20170708_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoor.Building')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indoor.Floor'),
        ),
        migrations.AddField(
            model_name='poi',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indoor.Floor'),
        ),
        migrations.AddField(
            model_name='roompolygon',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indoor.Floor'),
        ),
    ]
