# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0006_auto_20170709_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
