# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 05:50
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0007_floor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='graph_pickled_data',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
