# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0008_building_graph_pickled_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='graph_pickled_data',
            new_name='graph',
        ),
    ]
